apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense
data:
   DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:  # these are replicaset labels
    app: backend
    tier: api
    project: expense
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:   # these are used to select the pod to create replicas
      app: backend
      tier: api
      project: expense
  #this is pod defination    
  template:
    metadata:
      labels:  # these are pod labels
         app: backend
         tier: api
         project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: backend-config


---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
     app: backend
     tier: api
     project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port
