apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:  # these are replicaset labels
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:   # these are used to select the pod to create replicas
      app: mysql
      tier: db
      project: expense
  #this is pod defination    
  template:
    metadata:
      labels:  # these are pod labels
         app: mysql
         tier: db
         project: expense
    spec:
      containers:
      - name: mysql
        image: gopichand9534/mysql:v1